version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    container_name: idp.example.com
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      VIRTUAL_HOST: idp.example.com
      VIRTUAL_PORT: 8080
    networks:
    - reverse-proxy-net

networks:
  reverse-proxy-net:
    external: true