version: '3'
services:
  cap:
    build:
      context: ../../
      dockerfile: ./example/cap/Dockerfile
    hostname: cap1.ztf-proto.k3.ipv6.mobi
    environment:
      VIRTUAL_HOST: cap1.ztf-proto.k3.ipv6.mobi
    ports:
    - "80"
    networks:
    - reverse-proxy-net

networks:
  reverse-proxy-net:
    external: true