version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
    - reverse-proxy-net

networks:
  reverse-proxy-net:
    external: true